//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBASE_Smoketests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("API")]
        public string WorkspaceUser {
            get {
                return ((string)(this["WorkspaceUser"]));
            }
            set {
                this["WorkspaceUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkspacePassword {
            get {
                return ((string)(this["WorkspacePassword"]));
            }
            set {
                this["WorkspacePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TOSCA_PROJECTS\\TOSCA_Workspaces\\log\\")]
        public string LogfilePath {
            get {
                return ((string)(this["LogfilePath"]));
            }
            set {
                this["LogfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\tfdbnbld01\\LBase\\QA\\tosca\\Reports\\TestAPI\\")]
        public string ReportPath {
            get {
                return ((string)(this["ReportPath"]));
            }
            set {
                this["ReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tfdbnlx16")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
            set {
                this["Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QAUTF8")]
        public string SID {
            get {
                return ((string)(this["SID"]));
            }
            set {
                this["SID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Tosca_Projects\\Tosca_Workspaces\\lbase\\lbase.tws")]
        public string WorkspacePath {
            get {
                return ((string)(this["WorkspacePath"]));
            }
            set {
                this["WorkspacePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestAPI_TC11")]
        public string LogfileName {
            get {
                return ((string)(this["LogfileName"]));
            }
            set {
                this["LogfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lbase")]
        public string WorkspaceName {
            get {
                return ((string)(this["WorkspaceName"]));
            }
            set {
                this["WorkspaceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qualityassurance@lbase.software")]
        public string EMailAdresse {
            get {
                return ((string)(this["EMailAdresse"]));
            }
            set {
                this["EMailAdresse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMailAdresseCc {
            get {
                return ((string)(this["EMailAdresseCc"]));
            }
            set {
                this["EMailAdresseCc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMailAdresseBcc {
            get {
                return ((string)(this["EMailAdresseBcc"]));
            }
            set {
                this["EMailAdresseBcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestAPI")]
        public string ExecutionlistProperties {
            get {
                return ((string)(this["ExecutionlistProperties"]));
            }
            set {
                this["ExecutionlistProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkspaceLogging")]
        public string WhatLogging {
            get {
                return ((string)(this["WhatLogging"]));
            }
            set {
                this["WhatLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkoutable {
            get {
                return ((bool)(this["checkoutable"]));
            }
            set {
                this["checkoutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecution")]
        public string ExecutionlistProperties_template1 {
            get {
                return ((string)(this["ExecutionlistProperties_template1"]));
            }
            set {
                this["ExecutionlistProperties_template1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecutionFeatureTests")]
        public string ExecutionlistProperties_template2 {
            get {
                return ((string)(this["ExecutionlistProperties_template2"]));
            }
            set {
                this["ExecutionlistProperties_template2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecutionGuiTests")]
        public string ExecutionlistProperties_template3 {
            get {
                return ((string)(this["ExecutionlistProperties_template3"]));
            }
            set {
                this["ExecutionlistProperties_template3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecution_lbaseWeb")]
        public string ExecutionlistProperties_template4 {
            get {
                return ((string)(this["ExecutionlistProperties_template4"]));
            }
            set {
                this["ExecutionlistProperties_template4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecution_lbaseWebGuiTests")]
        public string ExecutionlistProperties_template5 {
            get {
                return ((string)(this["ExecutionlistProperties_template5"]));
            }
            set {
                this["ExecutionlistProperties_template5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OvernightExecutionSecondTest")]
        public string ExecutionlistProperties_template6 {
            get {
                return ((string)(this["ExecutionlistProperties_template6"]));
            }
            set {
                this["ExecutionlistProperties_template6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReproduceFailure")]
        public string ExecutionlistProperties_template7 {
            get {
                return ((string)(this["ExecutionlistProperties_template7"]));
            }
            set {
                this["ExecutionlistProperties_template7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestAPI")]
        public string ExecutionlistProperties_template8 {
            get {
                return ((string)(this["ExecutionlistProperties_template8"]));
            }
            set {
                this["ExecutionlistProperties_template8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockFileDelete {
            get {
                return ((bool)(this["LockFileDelete"]));
            }
            set {
                this["LockFileDelete"] = value;
            }
        }
    }
}
